### ISSUE TITLE
Interpolators version of the plugins cause lag.

### ISSUE THREAD

**Issue by Naozumi520** [Kuuuube/Kuuube-s-CHATTER-EXTERMINATOR#1]
Tablet: Veikk S640
Driver version: OpenTabletDriver v0.5.2.3
Plugin version: [Drivers Version 0.5.0.0, Plugin Version 0.2.0.0]
Playstyle: dragging
Interpolators Setting: Interpolators, Strength 6, Frequency 1000hz .
Filters Setting: Strength 2
(Filters and Interpolators is not enabled in the same time)

I have used the plugin for about a month and it worked perfectly, until I reinstall my driver cuz of reinstalled the windows.
After installed the driver and installed all the mod back I needed, the most weird thing happened: My osu! just getting lag and the latency was over 30!

Screenshots:
Filters on:
![image](https://user-images.githubusercontent.com/52615455/112860590-ce798100-9068-11eb-82ad-10fa1e220299.png)

Interpolators on:
![image](https://user-images.githubusercontent.com/52615455/112860502-b73a9380-9068-11eb-9cb6-298b4b4a972b.png)

(FPS and latency was affect about 2FPS when pressing the screenshot keys.)

**Comment by Naozumi520** [comment]
Oh also this will only happened when enable more than 1 plugins. And the filter has no matters even of how many plugins you have installed. I have no idea is this a new issues or not, I just remember I was able to enable the Interpolators with others plugin before.

**Comment by Kuuuube** [comment]
It looks like either your computer is having trouble handling the interpolator or the higher report rate is causing osu to have trouble because your computer can't handle both. This isn't an issue with OTD or the plugin though. If you want you can try manually installing v0.3.0 (which hasn't been merged with the plugin repo yet). It should be slightly more optimized so maybe it will help some.

**Comment by Naozumi520** [comment]
Oh I see, Yes it does help a bit on the performance. 
I also notice there's also an error that I haven't saw it before in OTD.
![image](https://user-images.githubusercontent.com/52615455/112864424-a5f38600-906c-11eb-80fa-9beef97d2ece.png)
This might not the problem of OTD or the plugin maybe as you say.
Anyway thankyou for helping me :D
I'll look more to see if there's other reason cause this.
Thankyou :D

**Comment by Kuuuube** [comment]
Well that error is from devocub antichatter. You may want to do `File > Reset Settings` and save then restart OTD since there could be broken settings. There is also a version of the tdfilters that is still pending merge to the plugin repo which could fix this error also https://github.com/OpenTabletDriver/TabletDriverFilters/releases/tag/v0.2.0. If the error continues you should make an issue on the tdfilters repo.
