### ISSUE TITLE
uses an entire CPU core

### ISSUE THREAD

**Issue by recallmenot** [Kuuuube/Kuuube-s-CHATTER-EXTERMINATOR#2]
Hello,
fantastic plugin, very responsive, only I'm having an issue.
OS: Manjaro stable CPU:2600k Tablet: CTH-480
when I load your plugin, the opentabletdriver daemon uses one entire CPU core, whether I select 150Hz or 1000Hz. 60Hz is choppy.
Even with the raw version this happens.
Had to switch to AbstractQbit Radial Follow, now OpenTabletDriver Daemon uses 0.4% of a CPU core while moving the pen but it doesn't feel as snappy as your plugin, more like the original Windows Wacom driver.
Is there any way to fix this?

**Comment by Kuuuube** [comment]
This is an OTD or dotnet issue not an issue with the plugin. There's been some issues with timers on linux for .net 6 so try updating to .net 6.0.4. You can also try using the git builds for OTD and this should be fixed in the 0.6.0.4 release of OTD.

The hz doesn't do anything here (unlike all other plugins) but due to limitations in how OTD handles interpolators I'm forced to have it in the smooth version of the filter.

If none of that helps you can try using the raw version of the filter then put hawku smoothing on-top. That should feel similar and you can actually adjust the hz there. Though it could still have the cpu issues.
